version: "3.9"

services:
  postgres-db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: moneymate_auth_service
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - auth_service
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d moneymate_auth_service"]
      interval: 30s
      timeout: 10s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - auth_service
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:root@postgres-db:5432/moneymate_auth_service?sslmode=disable", "up"]
    depends_on:
      - postgres-db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6381:6379"
    networks:
      - auth_service
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth_service:
    container_name: moneymate_auth_service
    build: .
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9999:9999"
      - "7777:7777"
    networks:
      - auth_service

networks:
  auth_service:
    external: true

volumes:
  postgres-data:
