version: "3.9"

services:
  postgres-db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: language_leap_auth_service
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - auth_service
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  migrate:
    image: migrate/migrate
    networks:
      - auth_service
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:root@postgres:5432/language_leap_auth_service?sslmode=disable", "up"]
    depends_on:
      - postgres-db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - auth_service

  auth_service:
    container_name: language_leap_auth_service
    build: .
    depends_on:
      - postgres-db
      - redis
    ports:
      - "9999:9999"
      - "7777:7777"
    networks:
      - auth_service

networks:
  auth_service:
    driver: bridge

volumes:
  postgres-data:
